### ISSUE TITLE
invisible badge option?

### ISSUE THREAD

**Issue by ChristianPetersen** [silentsoft/hits#15]
this is my first ever "issue", I write on github. And to be honest - I use git more or less as a backup and versioning-tool. 
I looked at the service you provide at hits.sh and this is exactly, what I was looking for. 
The only change, I would need is an option for an invisible badge. 

what is the best way to proceed? Should I click on "pull request", change the java source code and use the new code on my own server? What if someone else also needs this option?

I am really sorry, if this is a stupid question. 
Christian

**Comment by silentsoft** [comment]
Thank you for registering the issue. However, there are currently no plans to provide the feature you mentioned in this service.

A quicker way, rather than creating and modifying the invisible option yourself, would be to add the opacity style to the image tag you want to apply, as shown below.

```html
<img alt="Hits" src="https://hits.sh/github.com/silentsoft/hits.svg" style="opacity: 0;">
```

**Comment by ChristianPetersen** [comment]
That is a brilliant idea. Thank you!

mit den besten Grüßen,

Christian Petersen


Am Di., 30. Mai 2023 um 23:49 Uhr schrieb Hyesung Lee <
***@***.***>:
