### ISSUE TITLE
Colorpicker를 적용한다.

### ISSUE THREAD

**Issue by InSeong-So** [silentsoft/hits#3]
## 개요
> 컬러를 선택할 때 조금 더 사용자 경험을 높이기 위함

1. [react-color](https://casesandberg.github.io/react-color/)를 사용한다.
2. 컴포넌트 및 커스텀 훅을 만들어 중복된 코드를 제거한다.

<br>

## 관련 이슈
1. 드래그 이벤트 시 틱 당 서버로 요청이 가서 많은 부하가 걸리므로 이에 대한 이벤트 분리가 필요
    > [@silentsoft 님 코멘트 ](https://github.com/silentsoft/hits/pull/4#issuecomment-1036140900)

**Comment by silentsoft** [comment]
제가 딱 생각하고 있었던 디자인인데 시간 내주셔서 구현하시다니 ㅜㅜ 너무 감사드립니다 ! 👍 ❤️
